### PR TITLE
Bump aws-sdk-go and fix issue with global region for alternative partitions

### PR DESCRIPTION
**Pull request by yorinasub17**
## Description

Fixes bug where global resources error out for GovCloud.

## TODOs

Read the [Gruntwork contribution guidelines](https://gruntwork.notion.site/Gruntwork-Coding-Methodology-02fdcd6e4b004e818553684760bf691e).

- [x] Update the docs.
- [x] Run the relevant tests successfully, including pre-commit checks.
- [x] Ensure any 3rd party code adheres with our [license policy](https://www.notion.so/gruntwork/Gruntwork-licenses-and-open-source-usage-policy-f7dece1f780341c7b69c1763f22b1378) or delete this line if its not applicable.
- [x] Include release notes. If this PR is backward incompatible, include a migration guide.

## Release Notes (draft)

- Fixed bug where global resources were not nuked due to a broken security token issue when using GovCloud.

### CODE REVIEW

**Comment by yorinasub17** [comment]
I looked into the test failures, and they are all unrelated to this change. The following tests failed, and all of them are not global resources:

```
FAIL: TestListMacieAccounts
FAIL: TestListLaunchConfigurations
FAIL: TestListSqsQueue
FAIL: TestListAutoScalingGroups
```

**Review by zackproser — APPROVED** [review]
LGTM

**Comment by yorinasub17** [comment]
Thanks for review! Merging now.

**Comment by yorinasub17** [comment]
Released as https://github.com/gruntwork-io/cloud-nuke/releases/tag/v0.16.4

**Pull request merged**
