### PR TITLE
Adding support for nuking EFS file systems

### PR DESCRIPTION
**Pull request by robmorgan**
This PR is a **WIP**, however I wanted to open one to get early feedback.

### My questions

1. As an EFS file system has associated mount targets, should I delete them first (in `aws.go`. See the commented out code) or as part of the `nukeAllEfsFileSystems` function? Note: Essentially we need the EFS File System ID in order to be able to remove mount targets.
2. I have combined two seperate types in the `efs_types.go` file. Is that the correct behaviour or should I split them across two files.

### TODO

- [ ] Automated tests

### CODE REVIEW

**Comment by brikis98** [comment]
Just to make sure I understand the issue:

1. To be able to delete an EFS file system, you must first delete all the mount targets.
1. To be able to delete mount targets, you need all the EFS file system IDs first.
1. So you're asking if those two should be deleted as one unit or two separate items that, in principle, could be run independently?

**Comment by brikis98** [comment]
OK, thanks for the clarification. So is there ever a use case for _just_ deleting mount targets that's not associated with EFS? Or vice versa, deleting the EFS file system without first deleting mount targets? If there's no real-world scenario where that's likely, may as well keep them together and keep the code simple.

**Comment by robmorgan** [comment]
@brikis98 No I don't think there is and I guess the purpose of cloud-nuke is to destroy everything. You cannot delete the file system without first deleting the mount targets (and the mount targets are essentially useless without the FS).

**Comment by Etiene** [comment]
Just throwing in my two cents that then I also think it's OK to delete the mount targets together and have both types in one file.

**Comment by robmorgan** [comment]
@Etiene okay, noted 👍

**Comment by robmorgan** [comment]
I'm closing this for now and I'll either pick it back up again in the future, or somebody else can.

**Pull request closed without merging**
