### PR TITLE
register missing resource - TGW Peering Attachment

### PR DESCRIPTION
**Pull request by wakeful**
## Description
I was running `dead code` analysis and noticed that the `TransitGatewayPeeringAttachment` resource is not being used.

```sh

aws/resources/tgw_peering_attachment.go:14:46: unreachable func: TransitGatewayPeeringAttachment.getAll
aws/resources/tgw_peering_attachment.go:34:46: unreachable func: TransitGatewayPeeringAttachment.nukeAll
aws/resources/tgw_peering_attachment_types.go:22:46: unreachable func: TransitGatewayPeeringAttachment.Init
aws/resources/tgw_peering_attachment_types.go:26:46: unreachable func: TransitGatewayPeeringAttachment.ResourceName
aws/resources/tgw_peering_attachment_types.go:30:46: unreachable func: TransitGatewayPeeringAttachment.MaxBatchSize
aws/resources/tgw_peering_attachment_types.go:34:46: unreachable func: TransitGatewayPeeringAttachment.ResourceIdentifiers
aws/resources/tgw_peering_attachment_types.go:38:46: unreachable func: TransitGatewayPeeringAttachment.GetAndSetResourceConfig
aws/resources/tgw_peering_attachment_types.go:42:46: unreachable func: TransitGatewayPeeringAttachment.GetAndSetIdentifiers
aws/resources/tgw_peering_attachment_types.go:52:46: unreachable func: TransitGatewayPeeringAttachment.Nuke
```

## TODOs

Read the [Gruntwork contribution guidelines](https://gruntwork.notion.site/Gruntwork-Coding-Methodology-02fdcd6e4b004e818553684760bf691e).

- [x] Update the docs.
- [x] Run the relevant tests successfully, including pre-commit checks.
- [x] Ensure any 3rd party code adheres with our [license policy](https://www.notion.so/gruntwork/Gruntwork-licenses-and-open-source-usage-policy-f7dece1f780341c7b69c1763f22b1378) or delete this line if its not applicable.
- [x] Include release notes. If this PR is backward incompatible, include a migration guide.
- [ ] Attention Grunts - if this PR adds support for a new resource, ensure the `nuke_sandbox` and `nuke_phxdevops` jobs in `.circleci/config.yml` have been updated with appropriate exclusions (either directly in the job or via the `.circleci/nuke_config.yml` file) to prevent nuking IAM roles, groups, resources, etc that are important for the test accounts.

## Release Notes (draft)
Added `TransitGatewayPeeringAttachment` to be loaded.

### Migration Guide
n/a

### CODE REVIEW

**Review by james03160927 — DISMISSED** [review]
LGTM

**Comment by james03160927** [comment]
It seems like there are some merge conflict. We can submit it once it's resolved.

**Comment by wakeful** [comment]
> It seems like there are some merge conflict. We can submit it once it's resolved.

resolved

**Comment by wakeful** [comment]
hey @james03160927 

I added another commit to this MR with code changes to move the `transit-gateway-peering-attachment` resource to AWS SDK v2.

**Review by james03160927 — APPROVED** [review]
LGTM

**Pull request merged**
