### PR TITLE
Adding contribution guidelines

### PR DESCRIPTION
**Pull request by saurabh-hirani**
Adding contribution guidelines as per the discussion in https://github.com/gruntwork-io/cloud-nuke/issues/77

### CODE REVIEW

**Comment by brikis98** [comment]
@robmorgan Could you review?

**Comment by robmorgan** [comment]
thanks, I will review this week

**Comment by robmorgan** [comment]
Thanks for your PR, I have added a separate `CONTRIBUTING.md` file and made a bunch of changes to bring `cloud-nuke` more inline with our other open source repos.

This resolves issue #77.

**Comment by saurabh-hirani** [comment]
Thanks @robmorgan - having a separate contributon md file makes sense.

**Pull request merged**
