### PR TITLE
Fix CircleCI Contexts

### PR DESCRIPTION
**Pull request by zackproser**
This pull request was programmatically opened by the multi-repo-updater program. It should be adding the 'Gruntwork Admin' context to any Workflows -> Jobs nodes and should also be leaving the rest of the .circleci/config.yml file alone. 

 This PR was opened so that all our repositories' .circleci/config.yml files can be converted to use the same CircleCI context, which will make rotating secrets much easier in the future.

### CODE REVIEW

**Review by brikis98 — APPROVED** [review]
The code changes LGTM! 

However, I just realized that `cloud-nuke` has several sets of credentials (one for Phx DevOps, one for sandbox) and the `Gruntwork Admin` context only has the Phx DevOps ones for now... But I can add those in using the same env vars after this is merged.

**Comment by zackproser** [comment]
> The code changes LGTM!
> 
> However, I just realized that `cloud-nuke` has several sets of credentials (one for Phx DevOps, one for sandbox) and the `Gruntwork Admin` context only has the Phx DevOps ones for now... But I can add those in using the same env vars after this is merged.

Thanks @brikis98 - do we need to coordinate on this timing to avoid any failures, issues?

**Comment by brikis98** [comment]
I think it'll work fine to merge this... When, later, I go through and remove the env vars from each project, I'll need too remember to update Gruntwork Admin context accordingly.

**Comment by zackproser** [comment]
> I think it'll work fine to merge this... When, later, I go through and remove the env vars from each project, I'll need too remember to update Gruntwork Admin context accordingly.

Roger - merging!

**Pull request merged**
