### PR TITLE
#227 Fix TestDeleteFullIamUser

### PR DESCRIPTION
**Pull request by denis256**
Attempt to fix TestDeleteFullIamUser by adding retries in the assignment of MFA device

Execution result:
image

Fixes:
#227

### CODE REVIEW

**Comment by infraredgirl** [comment]
So this solution essentially retries enabling the MFA device 3 times, in hopes that it will eventually succeed. This could certainly improve the test, but I wonder if there's a better way to address the failure. 

Looking at the error in the original test failure: 
```
EntityTemporarilyUnmodifiable: MFA cannot be enabled while the Login Profile  for principal cloud-nuke-test-full-user-dsiSR3 is being created.
```
So it seems that the problem is a race condition between creating the Login Profile and enabling the MFA. Is there a way we can check/poll the results of the `CreateLoginProfile` call and ensure that the call to `EnableMFADevice` only happens one the Login Profile has been created?

**Comment by denis256** [comment]
Since `CreateLoginProfile` returns same completed structure each time, updated approach to detect in-progress profile creation by sending update requests and check errors

https://docs.aws.amazon.com/sdk-for-go/api/service/iam/

**Comment by infraredgirl** [comment]
Hmm, unfortunately the test failed with `'Verify if profile is ready' unsuccessful after 10 retries`. So, while adding retries does not guarantee to solve the issue with this test, I still think it's an improvement to the current state. I think we should go ahead and merge, but before doing so, maybe give it one last try of tweaking the timeout a bit. Right now it's 10 retries with 5 seconds in between, for a total of 50 seconds. Maybe try something like 4 retires with 30 seconds in between, a total of 2 minutes. What do you think @denis256?

**Comment by denis256** [comment]
Updated timing configurations

**Review by infraredgirl — APPROVED** [review]
Thanks, Denis, looks good! Approving and merging.

**Pull request merged**
