### PR TITLE
Change the order of cloud-nuke to delete IAM policy first before IAM groups

### PR DESCRIPTION
**Pull request by hongil0316**
Change the order of cloud-nuke to delete IAM policy first before IAM groups

## Description

Fixes https://gruntwork.atlassian.net/browse/CORE-330.

## Testing
* Created a test IAM policy and IAM group via AWS UI
* Inspected that both element exist by running the command: 

```
aws-vault exec demo-logs -- ./cloud-nuke inspect-aws --resource-type iam-policy --resource-type iam-group
```
* Ran the cloud-nuke command to delete both resources at the same time: 

```
aws-vault exec demo-logs -- ./cloud-nuke aws --resource-type iam-group --resource-type iam-policy 
```

Final confirmation from the cloud-nuke CLI: 

image

* Checked the AWS UI and verified both resources have been deleted successfully. 
Also, tested inline group policy deletion as well by manually creating an inline group policy AWS UI: 

image

## TODOs

Read the [Gruntwork contribution guidelines](https://gruntwork.notion.site/Gruntwork-Coding-Methodology-02fdcd6e4b004e818553684760bf691e).

- [x] Update the docs.
- [x] Run the relevant tests successfully, including pre-commit checks.
- [x] Ensure any 3rd party code adheres with our [license policy](https://www.notion.so/gruntwork/Gruntwork-licenses-and-open-source-usage-policy-f7dece1f780341c7b69c1763f22b1378) or delete this line if its not applicable.
- [x] Include release notes. If this PR is backward incompatible, include a migration guide.
- [x] Attention Grunts - if this PR adds support for a new resource, ensure the `nuke_sandbox` and `nuke_phxdevops` jobs in `.circleci/config.yml` have been updated with appropriate exclusions (either directly in the job or via the `.circleci/nuke_config.yml` file) to prevent nuking IAM roles, groups, resources, etc that are important for the test accounts.

## Release Notes (draft)

Added / Removed / Updated [X].
Updated [Updated the iam-group cloud-nuke operation to delete inline group policies]

### Migration Guide

No migration needed

### CODE REVIEW

**Review by ellisonc — DISMISSED** [review]
This was an issue with inline polices on the IAM group, can you add a test for that?

**Comment by arsci** [comment]
Can you update the description - todos and release notes section

**Comment by hongil0316** [comment]
> Can you update the description - todos and release notes section

Updated. Let me know if there's anything I missed!

**Comment by arsci** [comment]
> Hmm I tried to look through the API documentation and existing set of tests in the code base, but it doesn't seem like there's a way to create IAM group with inline policy.

I think you will need to use `PutGroupPolicy` for creating inline policies

https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/iam#PutGroupPolicy

**Review by arsci — APPROVED** [review]
LGTM

**Pull request merged**
