### PR TITLE
add aws v2 sdk to support newer resources (#745)

### PR DESCRIPTION
**Pull request by wakeful**
## Description

add support for Managed Prometheus and AWS SDK v2 #745 

## TODOs

Read the [Gruntwork contribution guidelines](https://gruntwork.notion.site/Gruntwork-Coding-Methodology-02fdcd6e4b004e818553684760bf691e).

- [x] Update the docs.
- [x] Run the relevant tests successfully, including pre-commit checks.
- [x] Ensure any 3rd party code adheres with our [license policy](https://www.notion.so/gruntwork/Gruntwork-licenses-and-open-source-usage-policy-f7dece1f780341c7b69c1763f22b1378) or delete this line if its not applicable.
- [x] Include release notes. If this PR is backward incompatible, include a migration guide.
- [ ] Attention Grunts - if this PR adds support for a new resource, ensure the `nuke_sandbox` and `nuke_phxdevops` jobs in `.circleci/config.yml` have been updated with appropriate exclusions (either directly in the job or via the `.circleci/nuke_config.yml` file) to prevent nuking IAM roles, groups, resources, etc that are important for the test accounts.

## Release Notes (draft)

add support for `Managed Prometheus` & start using `AWS SDK v2`

### CODE REVIEW

**Comment by james03160927** [comment]
Hi @wakeful, do you plan to make continuous progress on this PR?

**Comment by wakeful** [comment]
hey @james03160927 

Initially, I marked this PR as `WIP` to start a discussion on the new version of the **SDK**. If my approach to introducing **SDK V2** is agreeable, I will resolve the conflicts and add tests. The main logic remains unchanged.

You should receive an updated PR before the end of this week.

**Review by james03160927 — COMMENTED** [review]
Overall approach LGTM. 
Let's ensure to add tests for managed_prometheus file as well.

**Comment by wakeful** [comment]
hey @james03160927 

Sorry for the late reply!
I finally found some time to add the missing tests.

**Review by james03160927 — APPROVED** [review]
LGTM

**Pull request merged**
