### PR TITLE
VPC config file support

### LINKED ISSUE #246: VPC nuke should honor the config file

### PR DESCRIPTION
**Pull request by tonerdo**
Fixes #246

### CODE REVIEW

**Comment by denis256** [comment]
I was wondering if make sense to implement additional tests to verify inclusion/exclusion rules

**Review by brikis98 — COMMENTED** [review]
+1 on adding _some_ sort of testing for this

**Comment by tonerdo** [comment]
@brikis98 any reason we don't already have tests that spin up and nuke VPCs? It seemed odd and I'm happy to add, just don't want to go down a rabbit hole if someone else has already been there..

**Comment by brikis98** [comment]
> @brikis98 any reason we don't already have tests that spin up and nuke VPCs? It seemed odd and I'm happy to add, just don't want to go down a rabbit hole if someone else has already been there.

Huh. I'm not sure. Seems like an oversight, TBH!

**Comment by tonerdo** [comment]
Tests added! cc @denis256 @brikis98

**Review by denis256 — APPROVED** [review]

**Pull request merged**
