### PR TITLE
Add ECS config file support

### PR DESCRIPTION
**Pull request by brandonstrohmeyer**
Add support to filter ECS Clusters and Services by name in config file.

Test output:
https://gist.github.com/brandonstrohmeyer/e3bc64ebf9d2ac98c055ec48fc7180f2

### CODE REVIEW

**Review by denis256 — DISMISSED** [review]
Added test passes and cover filtering functionality

**Comment by denis256** [comment]
https://github.com/gruntwork-io/cloud-nuke/pull/261/files#r768149940

**Review by denis256 — APPROVED** [review]

**Comment by yorinasub17** [comment]
LGTM as well! I'll kick off a sanity check regression build now and if that passes, we can merge this in! Thanks for your contribution!

**Comment by yorinasub17** [comment]
Build failed, but it's for an unrelated resource test, so it effectively passed. However, as mentioned on the ELBv2 version of this (https://github.com/gruntwork-io/cloud-nuke/pull/261), there is a merge conflict, so consider combining the two PRs together.

**Comment by brandonstrohmeyer** [comment]
> Build failed, but it's for an unrelated resource test, so it effectively passed. However, as mentioned on the ELBv2 version of this (#261), there is a merge conflict, so consider combining the two PRs together.


I opened #266 as a combined PR. Originally I wasn't sure if it was better to submit each individual config file "feature" as an individual PR, but it seems that creates more problems than it solves so will lean toward larger PRs in the future. 

Thanks!

**Pull request closed without merging**
