### PR TITLE
Skip if tag value is empty or set to true

### LINKED ISSUE #822: Feature Request: Exclude Resources by Tag Existence
### Feature Request: Exclude Resources by Tag Existence in Cloud Nuke

**Current Behavior:**
Cloud Nuke currently supports excluding resources based on a specified key only if its value is `"true"`.

**Feature Request:**
Add support for excluding resources based on the existence of a tag key, regardless of its value.

**Use Case:**
For example, if a resource has the tag `Component: rds`, I would like to exclude it by specifying `isTagExist: Component`. This ensures that all resources with the key `Component` (regardless of its value) are excluded from nuking.

**Proposed Solution:**
Introduce a new parameter `isTagExist` that accepts a tag key. If the specified key exists on a resource, the resource will be excluded.

**Benefits:**
- Provides more flexibility for users to manage exclusions.
- Simplifies scenarios where values of tags are dynamic or irrelevant.

**Example Configuration:**
```yaml
excludeTags:
  isTagExist: Component
```

Would exclude any resource with the tag `Component` present, such as:
- `Component: rds`
- `Component: database`
- `Component: test`

Let me know if more details are needed!

### PR DESCRIPTION
**Pull request by wakeful**
## Description

Fixes #822, change the exclude by tag behaviour to allow matching by an empty tag value.

## TODOs

Read the [Gruntwork contribution guidelines](https://gruntwork.notion.site/Gruntwork-Coding-Methodology-02fdcd6e4b004e818553684760bf691e).

- [x] Update the docs.
- [x] Run the relevant tests successfully, including pre-commit checks.
- [x] Ensure any 3rd party code adheres with our [license policy](https://www.notion.so/gruntwork/Gruntwork-licenses-and-open-source-usage-policy-f7dece1f780341c7b69c1763f22b1378) or delete this line if its not applicable.
- [x] Include release notes. If this PR is backward incompatible, include a migration guide.
- [ ] Attention Grunts - if this PR adds support for a new resource, ensure the `nuke_sandbox` and `nuke_phxdevops` jobs in `.circleci/config.yml` have been updated with appropriate exclusions (either directly in the job or via the `.circleci/nuke_config.yml` file) to prevent nuking IAM roles, groups, resources, etc that are important for the test accounts.

## Release Notes (draft)
change the `exclude by tag` behaviour to allow matching by an empty tag value, fix #822.

### Migration Guide
n/a

### CODE REVIEW

**Review by james03160927 — COMMENTED** [review]
I suggest changing the existing behavior slightly: if the exclusion tag has no value, we should assume the tag itself indicates that the resource should be excluded. If a value is present, we should check whether it is set to "true."

**Comment by wakeful** [comment]
> I suggest changing the existing behavior slightly: if the exclusion tag has no value, we should assume the tag itself indicates that the resource should be excluded. If a value is present, we should check whether it is set to "true."

Agreed, this simplifies the whole logic quite a lot.

**Comment by james03160927** [comment]
https://github.com/gruntwork-io/cloud-nuke/issues/822#issuecomment-2562274489 - To accommodate this, we could introduce a TagValue property within the FilterRule. The TagValue could default to true, be set to a specific value being targeted, or use *, indicating that it can match any value.

How does this sound?

**Comment by wakeful** [comment]
> [#822 (comment)](https://github.com/gruntwork-io/cloud-nuke/issues/822#issuecomment-2562274489) - To accommodate this, we could introduce a TagValue property within the FilterRule. The TagValue could default to true, be set to a specific value being targeted, or use *, indicating that it can match any value.
> 
> How does this sound?

I added `tag_value` to the configuration as a regular expression, primarily because there is already a `matches(name string, regexps []Expression) bool` function.


The original request should now be easy to address using this configuration. cc: @ErezWeiss
```yaml
s3:
  exclude:
    tag: Component
    tag_value: .*
```

**Comment by ErezWeiss** [comment]
@james03160927
@wakeful 
 it seems amazing.
Can we proceed?

**Review by james03160927 — APPROVED** [review]
LGTM. Passed all the tests.

**Comment by ErezWeiss** [comment]
@james03160927 thank you.
Can you guys build a version for it?

**Pull request merged**
