### PR TITLE
port SQS & SNS to awsSDKv2

### PR DESCRIPTION
**Pull request by wakeful**
## Description

- Migrate **SQS** & **SNS** to **awsSDKv2**
- add report to track progress off **awsSDKv2** migration

## TODOs

Read the [Gruntwork contribution guidelines](https://gruntwork.notion.site/Gruntwork-Coding-Methodology-02fdcd6e4b004e818553684760bf691e).

- [x] Update the docs.
- [x] Run the relevant tests successfully, including pre-commit checks.
- [x] Ensure any 3rd party code adheres with our [license policy](https://www.notion.so/gruntwork/Gruntwork-licenses-and-open-source-usage-policy-f7dece1f780341c7b69c1763f22b1378) or delete this line if its not applicable.
- [x] Include release notes. If this PR is backward incompatible, include a migration guide.
- [ ] Attention Grunts - if this PR adds support for a new resource, ensure the `nuke_sandbox` and `nuke_phxdevops` jobs in `.circleci/config.yml` have been updated with appropriate exclusions (either directly in the job or via the `.circleci/nuke_config.yml` file) to prevent nuking IAM roles, groups, resources, etc that are important for the test accounts.

## Release Notes (draft)

Updated **SQS** & **SNS** to **AWS SDK v2**.
Added **AWS SDK v2** migration report.

### Migration Guide

n/a

### CODE REVIEW

**Review by james03160927 — COMMENTED** [review]
Hi @wakeful, thanks for the contribution. Can you explain why we want to migrate everything to SDK v2? That would be quite a lot of work.

**Comment by wakeful** [comment]
> Hi @wakeful, thanks for the contribution. Can you explain why we want to migrate everything to SDK v2? That would be quite a lot of work.

hey @james03160927 

As I mentioned in #745, the AWS SDK v1 is **officially deprecated** (end-of-support is July 31, 2025).
This is the first PR to show how easy the migration is and to provide some visibility (report generator).

I agree that this migration is quite a lot of work, yet this tool is vital for many of my projects (and possibly for others as well).

I have patches ready for a few more services (I'm currently testing them in my own environment).
- API GWv1
- API GWv2
- ASG
- access_analyzer
- acm
- acmpca
- ami
- appRunner
- backup vault
- cloudTrail
- cloudWatch alarm
- cloudWatch dashboard
- cloudWatch logGroup
- codeDeploy Application
- config recorder
- config service
- dataSync location
- dataSync task
- dynamodb

**Comment by james03160927** [comment]
> > Hi @wakeful, thanks for the contribution. Can you explain why we want to migrate everything to SDK v2? That would be quite a lot of work.
> 
> hey @james03160927
> 
> As I mentioned in #745, the AWS SDK v1 is **officially deprecated** (end-of-support is July 31, 2025). This is the first PR to show how easy the migration is and to provide some visibility (report generator).
> 
> I agree that this migration is quite a lot of work, yet this tool is vital for many of my projects (and possibly for others as well).
> 
> I have patches ready for a few more services (I'm currently testing them in my own environment).
> 
> * API GWv1
> * API GWv2
> * ASG
> * access_analyzer
> * acm
> * acmpca
> * ami
> * appRunner
> * backup vault
> * cloudTrail
> * cloudWatch alarm
> * cloudWatch dashboard
> * cloudWatch logGroup
> * codeDeploy Application
> * config recorder
> * config service
> * dataSync location
> * dataSync task
> * dynamodb

Got it. Thanks for the context. If that's the case, I can definitely help migrating over remaining services to version V2.

**Comment by james03160927** [comment]
Also created an issue for me to keep track of the progress. https://github.com/gruntwork-io/cloud-nuke/issues/770

**Comment by james03160927** [comment]
I can help to migrate changes from bottom up since it seems like you are doing form top to bottom.

**Pull request merged**
